name: dorm_fix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
workspace:
  - packages/ui_kit

environment:
  sdk: ^3.11.0-16.0.dev

dependencies:
  flutter:
    sdk: flutter

  # Internationalization and localization support
  flutter_localizations:
    sdk: flutter  
    
  intl: ^0.20.2
  # UI Kit
  ui_kit:
    path: packages/ui_kit
  # BLoC
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  # Route
  auto_route: ^10.1.2
  # Firebase
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.1
  # Google sign in
  google_sign_in: ^7.2.0
  # Logs
  logger: ^2.6.2
  # RX
  rxdart: ^0.28.0
  # Yandex MapKit
  yandex_mapkit: ^4.2.1
  # Http clients  
  http: ^1.5.0
  cronet_http: ^1.6.0
  cupertino_http: ^2.3.0
  # Local storage
  shared_preferences: ^2.5.3
  # Image picker
  image_picker: ^1.2.1
  video_player: ^2.10.1
  mime: ^2.0.0
  animations: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - packages/ui_kit/assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: packages/ui_kit/fonts/Inter_Bold.ttf
          weight: 700
        - asset: packages/ui_kit/fonts/Inter_Medium.ttf
          weight: 500
        - asset: packages/ui_kit/fonts/Inter_Regular.ttf
          weight: 400
        - asset: packages/ui_kit/fonts/Inter_SemiBold.ttf
          weight: 600
