name: ui_kit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.11.0-16.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_Bold.ttf
          weight: 700
        - asset: fonts/Inter_Medium.ttf
          weight: 500
        - asset: fonts/Inter_Regular.ttf
          weight: 400
        - asset: fonts/Inter_SemiBold.ttf
          weight: 600
